[package]
name = "dynamodb-helper"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.46"
quote = "1.0.20"
syn = { version = "1.0.98", features = ["extra-traits"]}

[lib]
proc-macro = true
