name: DynamoDB Helper Build
on:
  workflow_dispatch:
  push:
    branches:
      - master

env:
  PROJECT_NAME: dynamodb_helper

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Start the local dynamodb container
        run: nohup docker run --rm -p 8000:8000 amazon/dynamodb-local &
      - name: Run all tests
        run: cargo test

#  publish:
#    needs:
#      - test
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions-rs/cargo@v1
#        with:
#          command: login
#          args: ${{ secrets.CRATES_TOKEN }}
#      - name: Publish to cargo
#        run: cargo publish
